#! /bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

# scan sys and populate dev
/sbin/mdev -s

#/bin/mkdir -m 0755 /dev/pts
#/bin/touch /var/log/wtemp

# configure network
#/sbin/ifconfig lo up
#/sbin/ifconfig eth0 192.168.1.11

for i in 1 2 ; do
	echo $i  > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio$i/direction
done

for i in 3 4 ; do
	echo $i > /sys/class/gpio/export
	echo in > /sys/class/gpio/gpio$i/direction
done

