#! /bin/sh

# mount filesystems
mount -t proc none /proc
mount -t sysfs none /sys

# scan sys and populate dev
/sbin/mdev -s

# misc
/bin/mkdir -m 0755 /dev/pts
#/bin/touch /var/log/wtemp

# configure network
#/sbin/ifconfig lo up
#/sbin/ifconfig eth0 192.168.1.11

# start misc daemons
#/usr/sbin/telnetd

# define GPIOs
for i in 0 1 2 3 8 9 10 11 ; do
	echo $i  > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio$i/direction
done
for i in 4 5 6 7 12 13 14 15 ; do
	echo $i > /sys/class/gpio/export
	echo in > /sys/class/gpio/gpio$i/direction
done

